name: Discord

on: 
  release:
    types: [published]

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        username: "R2D2"
        message: "Une nouvelle version du jeu est désormais en ligne."
